Changed configuration and added logging.

diff --git a/src/bash/db-backup b/src/bash/db-backup
--- a/src/bash/db-backup
+++ b/src/bash/db-backup
@@ -38,6 +38,34 @@ Examples:
 EOF
 }
 
+LOG_FILE="/tmp/db-backup-$RANDOM.log"
+echo "Writing into the log file: $LOG_FILE"
+
+# Define a function to be called at the end of the script
+function cleanup {
+  echo "Cleaning up..."
+  rm -f $LOG_FILE
+}
+
+# Register the cleanup function to be called on script exit
+trap cleanup EXIT
+
+function write {
+  echo -e "$1"
+
+  no_color=$(echo -e "$1" | awk '{gsub(/\033\[[0-9;]*m/,"")}1')
+  if [[ $1 == *"\c" ]]; then
+    echo -ne "$no_color" >> $LOG_FILE
+  else
+    echo -e "$no_color" >> $LOG_FILE
+  fi
+}
+
+function log {
+  cas=$(date +"%H:%M:%S")
+  write "[$cas] $1"
+}
+
 # Loop through options and assign values
 while [[ "$#" -gt 0 ]]; do
     case $1 in
@@ -85,7 +113,7 @@ fi
 # shellcheck disable=SC2068
 for CONFIG_FILE in ${CONFIG_FILES[@]}; do
 
-    CONFIG_NAME=$(basename "$CONFIG_FILE" | cut -d'.' -f1)
+    BACKUP_NAME=$(basename "$CONFIG_FILE" | cut -d'.' -f1)
 
     # Check if the config file exists
     if [ ! -f "$CONFIG_FILE" ]; then
@@ -105,17 +133,28 @@ for CONFIG_FILE in ${CONFIG_FILES[@]}; do
         exit 1
     fi
 
-    # Delete old backups
-    find $BACKUP_DIR -name "*.sql.gz" -mtime +$KEEP_BACKUPS_DAYS -type f -delete
+    touch $LOG_FILE
 
-    # Create backup subdirectory
     DATE_TIME=$(date +"%Y-%m-%d_%H%M%S")
     if [ -n "$RETENTION_POLICY" ]; then
-        BACKUP_SUBDIR="${BACKUP_SUBDIR_PREFIX}_${DATE_TIME}_${RETENTION_POLICY}"
+        BACKUP_SUBDIR="${BACKUP_NAME}_${DATE_TIME}_${RETENTION_POLICY}"
     else
-        BACKUP_SUBDIR="${BACKUP_SUBDIR_PREFIX}_${DATE_TIME}"
+        BACKUP_SUBDIR="${BACKUP_NAME}_${DATE_TIME}"
     fi
     BACKUP_SUBDIR_FULL="$BACKUP_DIR/$BACKUP_SUBDIR"
+
+    clear
+
+    write "***************************************"
+    write "DATABASE BACKUP CREATION"
+    write "***************************************"
+    write "Date         : $(date +'%F %X')"
+    write "Backup name  : $BACKUP_NAME"
+    write "Database     : $DB_HOST:$DB_PORT"
+    write "Backup dir   : $BACKUP_SUBDIR_FULL"
+    write "***************************************\n"
+
+    # Create backup subdirectory
     mkdir -p "$BACKUP_SUBDIR_FULL"
 
     # Initialize the array to store failed backups' information
@@ -128,34 +167,46 @@ for CONFIG_FILE in ${CONFIG_FILES[@]}; do
         BACKUP_FILE="$BACKUP_SUBDIR_FULL/$FILENAME"
 
         # Print backup start message
-        echo -n "Database: $DB ... "
+        log "Database: $DB ... \c"
 
         # Run mysqldump to create backup
-        mysqldump -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" -p"$DB_PASSWORD" --single-transaction --routines --triggers --events "$DB" | gzip > "$BACKUP_FILE"
+        mysqldump \
+          -h "$DB_HOST" \
+          -P "$DB_PORT" \
+          -u "$DB_USER" \
+          -p"$DB_PASSWORD" \
+          --single-transaction \
+          --routines \
+          --triggers \
+          --events "$DB" \
+          | gzip > "$BACKUP_FILE"
+
 
         # Print backup end message
         if [[ ${PIPESTATUS[0]} -eq 0 ]]; then
-            echo -e "\033[32mdone\033[0m"
+            write "\033[32mdone\033[0m"
         else
             # Add failed backup's information to the array
-            FAILED_BACKUPS+=("$CONFIG_NAME.$DB")
+            FAILED_BACKUPS+=("$BACKUP_NAME.$DB")
 
-            echo -e "\033[31mfailed\033[0m"
+            write "\033[31mfailed\033[0m"
         fi
 
     done
 
     # Print completion message
-    echo "Backups of $CONFIG_NAME completed to: $BACKUP_SUBDIR_FULL"
+    write "Backups of $BACKUP_NAME completed to: $BACKUP_SUBDIR_FULL"
+
+    cp "$LOG_FILE" "$BACKUP_SUBDIR_FULL/db-backup.log"
 
 done
 
 # Print out the number of failed backups and their information (if any)
 if [ ${#FAILED_BACKUPS[@]} -eq 0 ]; then
-    echo -e "\nAll database backups completed successfully."
+    write "\nAll database backups completed successfully."
 else
-    echo -e "\n${#FAILED_BACKUPS[@]} backups failed:"
+    write "\n${#FAILED_BACKUPS[@]} backups failed:"
     for failed_backup in "${FAILED_BACKUPS[@]}"; do
-        echo "$failed_backup"
+        write "$failed_backup"
     done
 fi
